name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t my-docker-app .

      - name: Run the Docker image
        run: |
          docker run -d -p 3000:3000 my-docker-app

      - name: Health check
        run: |
          sleep 5
          curl -f http://localhost:3000 || exit 1
